name: 'CI'
on: 
  push:
    branches: 
      - master

jobs:
  build:
    
    runs-on: ubuntu-lastest
    steps:
      - uses: actions/checkout@v2
      - name: Push to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SERVER_IP}}
          username: ${{secrets.SERVER_USERNAME}}
          password: ${{secrets.SERVER_PASSWORD}}
          port: ${{secrets.PORT}}
          script: cd ${{secrets.PROJECT_PATH }} && git pull
        


